In [1]:
%%time
list_py = list(range(5000000))
list_py_5th = [x**5 for x in list_py]

CPU times: user 1.54 s, sys: 166 ms, total: 1.71 s
Wall time: 2.43 s


In [2]:
import numpy as np

In [3]:
%%time
array_np = np.arange(5000000)
array_np_5th = array_np ** 5

CPU times: user 19.5 ms, sys: 15.8 ms, total: 35.3 ms
Wall time: 45.2 ms


In [4]:
type(array_np)

numpy.ndarray

In [5]:
array_np.ndim

1

In [6]:
array_np.shape

(5000000,)

In [7]:
array_np.dtype

dtype('int64')

In [8]:
x= np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
x.dtype

dtype('int64')

In [10]:
x[5]

5

In [11]:
x[5]=1000

In [12]:
print(x)

[   0    1    2    3    4 1000    6    7    8    9]


In [13]:
x[5]='10000'

In [14]:
print(x)

[    0     1     2     3     4 10000     6     7     8     9]


In [16]:
x[5]='hello'
print(x)

TypeError: 'str' object does not support item assignment

In [17]:
x[5]='1003.33'
print(x)

TypeError: 'str' object does not support item assignment

In [18]:
x=[1,2,3,4,5]
y= np.array(x)

In [19]:
print(y)

[1 2 3 4 5]


In [20]:
y.dtype

dtype('int64')

In [21]:
x=[[1,2,3], [4,5,6]]
y=np.array(x)
print(y)

[[1 2 3]
 [4 5 6]]


In [22]:
y.ndim

2

In [23]:
y.dtype

dtype('int64')

In [24]:
y.shape

(2, 3)

In [25]:
y[1][1]

5

In [26]:
y[1,1]

5

In [27]:
y= np.array(x, dtype=np.float64)
print(y)

[[1. 2. 3.]
 [4. 5. 6.]]


In [28]:
y= np.array(x)
y.dtype

dtype('int64')

In [29]:
y_float = y.astype(np.float64)
y_float.dtype

dtype('float64')

In [30]:
x = np.array(['1.2','2'])
y= x.astype(np.float64)
z= y.astype(np.int32)
print(z)

[1 2]


In [31]:
x= np.ones((2,3))

In [32]:
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]


In [34]:
x= np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [35]:
x=[[1,2,3],
   [4,5,6]]
y= np.zeros_like(x)
z= np.ones_like(x)
print(y)

[[0 0 0]
 [0 0 0]]


In [36]:
print(z)

[[1 1 1]
 [1 1 1]]


In [37]:
x= np.eye(4)
print(x)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [38]:
x= np.arange(10)
y= x.reshape(5,2)
print(x)
print(y)

[0 1 2 3 4 5 6 7 8 9]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [39]:
x= np.arange(12).reshape(3,4)

In [40]:
x+10

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21]])

In [43]:
y= np.arange(11,-1,-1).reshape(3,4)

In [44]:
y

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

In [45]:
x+y

array([[11, 11, 11, 11],
       [11, 11, 11, 11],
       [11, 11, 11, 11]])

In [46]:
x*y

array([[ 0, 10, 18, 24],
       [28, 30, 30, 28],
       [24, 18, 10,  0]])

In [47]:
x[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [48]:
bool_x = np.array([False, True, False])

In [49]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
x[bool_x]

array([[4, 5, 6, 7]])

In [51]:
bool_y = np.array([True, False, True, False])

In [53]:
x[:, bool_y]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [54]:
x.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [56]:
 x= np.where(x>0 ,1 ,x)

In [57]:
x

array([[0, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [61]:
y= np.random.randn(6,7)

In [62]:
y

array([[ 0.27868754, -1.03664913,  2.33041643, -1.3978949 , -2.04270383,
         0.62378337, -1.41350965],
       [-0.93997376, -0.71696392, -0.12642426,  0.14864512,  0.4930786 ,
        -0.37772812,  0.43558316],
       [ 0.27836839,  0.93818597, -2.72063439,  1.0502766 ,  0.27911051,
        -0.06235798,  0.26038729],
       [ 1.10849347,  1.15890518, -0.53631584,  0.65216957, -0.16189594,
         1.90527957, -1.01975867],
       [ 0.15654571, -0.92392154,  0.41559039,  0.61970107, -1.25923522,
        -0.16148813,  0.05252   ],
       [ 0.84556908,  1.64608063,  1.38086174, -0.72995892,  0.26725843,
        -1.08757654, -0.64001084]])

In [63]:
np.mean(x)

0.9166666666666666

In [64]:
np.sum(x)

11

In [65]:
np.std(x)

0.2763853991962833

In [66]:
np.var(x)

0.07638888888888888

In [68]:
np.mean(y, axis=0)

array([ 0.2879484 ,  0.1776062 ,  0.12391568,  0.05715643, -0.40406457,
        0.13998536, -0.38746478])

In [69]:
np.mean(y, axis=1)

array([-0.37969574, -0.15482617,  0.00333377,  0.44383962, -0.15718396,
        0.24031766])